src/Areas/Admin/Controllers/MusicianController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicViet.DataModel;
using System.IO;

namespace MusicViet.Areas.Admin.Controllers
{
    public class MusicianController : Controller
    {
        private MusicDbContext db = new MusicDbContext();

        // GET: /Admin/Musician/
        public ActionResult Index()
        {
            return View(db.Musicians.ToList());
        }

        // GET: /Admin/Musician/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musician musician = db.Musicians.Find(id);
            if (musician == null)
            {
                return HttpNotFound();
            }
            return View(musician);
        }

        // GET: /Admin/Musician/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Admin/Musician/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MusicianName,MusicianStory")]Musician musician, HttpPostedFileBase upload)
        {
            try
            {
                if (upload.ContentLength > 0)
                {
                    string filename = Path.GetFileName(upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/ImageUpload/"), filename);
                    upload.SaveAs(path);
                    musician.MusicianPic = "~/ImageUpload/" + filename;
                    db.Musicians.Add(musician);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                   
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Loi upload File";
                return View();
            }
            return View();
        }

        // GET: /Admin/Musician/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musician musician = db.Musicians.Find(id);
            if (musician == null)
            {
                return HttpNotFound();
            }
            return View(musician);
        }

        // POST: /Admin/Musician/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="MusicianId,MusicianName,MusicianPic,MusicianStory")] Musician musician)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musician).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(musician);
        }

        // GET: /Admin/Musician/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musician musician = db.Musicians.Find(id);
            if (musician == null)
            {
                return HttpNotFound();
            }
            return View(musician);
        }

        // POST: /Admin/Musician/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Musician musician = db.Musicians.Find(id);
            db.Musicians.Remove(musician);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/Areas/Admin/Views/Musician/Create.cshtml
@model MusicViet.DataModel.Musician


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "Musician", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Thêm mới nhạc sĩ</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicianName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicianName)
                    @Html.ValidationMessageFor(model => model.MusicianName)
                </div>
            </div>
    
            <div class="form-group">
                @Html.Label("Chon anh nghe si", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="upload" id="Avatar" />
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicianStory, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.MusicianStory, new { @class = "form-control", @rows = "10" })
                    @Html.ValidationMessageFor(model => model.MusicianStory)
                </div>
            </div>
            <p style="color:red;">@ViewBag.Error</p>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Quay Lại", "Index")
    </div>
</body>
</html>

src/Areas/Admin/Views/Musician/Delete.cshtml
@model MusicViet.DataModel.Musician



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Bạn có muốn xóa Nhạc sĩ này không</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MusicianName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicianName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MusicianPic)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicianPic)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MusicianStory)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicianStory)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-default", role = "button" })
            </div>
        }
    </div>
</body>
</html>

src/Areas/Admin/Views/Musician/Details.cshtml
@model MusicViet.DataModel.Musician



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Musician</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MusicianName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicianName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MusicianPic)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicianPic)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MusicianStory)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicianStory)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.MusicianId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

src/Areas/Admin/Views/Musician/Edit.cshtml
@model MusicViet.DataModel.Musician

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Musician</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.MusicianId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicianName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicianName)
                    @Html.ValidationMessageFor(model => model.MusicianName)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicianPic, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicianPic)
                    @Html.ValidationMessageFor(model => model.MusicianPic)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicianStory, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicianStory)
                    @Html.ValidationMessageFor(model => model.MusicianStory)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

src/Areas/Admin/Views/Musician/Index.cshtml
@model IEnumerable<MusicViet.DataModel.Musician>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2 style="font-size:20px; text-align:center; font-weight: 600;">DANH SÁCH NHẠC SĨ</h2>
    <p>
        @Html.ActionLink("Thêm mới", "Create", new object { }, new { @class = "btn btn-info", role="button"})
    </p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MusicianName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MusicianStory)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:15%;">
                        @Html.DisplayFor(modelItem => item.MusicianName)
                    </td>
                    <td >
                        @Html.DisplayFor(modelItem => item.MusicianStory)
                    </td>
                    <td style="width:15%;">
                        @Html.ActionLink("Sửa", "Edit", new { id = item.MusicianId }) |
                        @Html.ActionLink("Chi tiết", "Details", new { id = item.MusicianId }) |
                        @Html.ActionLink("Xóa", "Delete", new { id = item.MusicianId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>