src/Areas/Admin/Controllers/HomeController.cs
using MusicViet.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Admin/Home/

        MusicDbContext db = new MusicDbContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            Session["username"] = null;
            Session["fullname"] = null;
            Session["avatar"] = null;
            Session["userId"] = null;
            string passwordMD5 = BcryptUser.EncryptMd5(username + password);
            var user = db.Accounts.SingleOrDefault(x => x.Username == username && x.Password == password && x.IsAdmin == 1);
            if (user != null)
            {
                Session["userid"] = user.UserId;
                Session["username"] = user.Username;
                Session["fullname"] = user.Fullname;
                Session["avatar"] = user.Avatar;
                return RedirectToAction("Index");
            }
            ViewBag.Error = "Đăng nhập sai hoặc bạn có quyền này";
            return View();
        }
        public ActionResult Logout()
        {
            Session["userid"] = null;
            Session["username"] = null;
            Session["fullname"] = null;
            Session["avatar"] = null;
            return View("Login");
        }
    }
}

src/Controllers/DetailArtistController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class DetailArtistController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        //
        // GET: /DetailArtist/
        public ActionResult Detail(int id, string artist)
        {
            
            Artist art = new Artist();
            if (artist == "singer")
            {
                var NameArtist = db.Singers.SingleOrDefault(x=>x.SingerId == id).SingerName;
                var PathArtist = db.Singers.SingleOrDefault(x => x.SingerId == id).SingerPic;
                var story = db.Singers.SingleOrDefault(x => x.SingerId == id).SingerStory;
                var SongOfArtist = db.Songs.Where(x => x.SingerId == id).ToList();
                art.Story = story;
               art.NameArtist = NameArtist;
               art.PathArtist = PathArtist;
               art.listSong = SongOfArtist;
              
            }
            if (artist == "musician")
            {
                var Artist = db.Musicians.SingleOrDefault(x => x.MusicianId == id).MusicianName;
                var PathArtist = db.Musicians.SingleOrDefault(x => x.MusicianId == id).MusicianPic;
                var story = db.Musicians.SingleOrDefault(x => x.MusicianId == id).MusicianStory;
                var SongOfArtist = db.Songs.Where(x => x.MusicianId == id).ToList();
                art.NameArtist = Artist[1].ToString();
                art.PathArtist = Artist[2].ToString();
                art.listSong = SongOfArtist;
                art.Story = story;
            }
            ViewBag.Artist = art;
            return View();
        }
	}
}

src/Controllers/DetailSongController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class DetailSongController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        //
        // GET: /DetailSong/
        public ActionResult Detail(int id)
        {
            Song song1 = new Song();
            // Lay bai hat tu cdsl
            song1 = db.Songs.Where(s => s.SongId == id).FirstOrDefault<Song>();
            // Lay so luot view cho bai hat va tang view len 1
            var views = (from song in db.Songs
                         join sing in db.Singers on song.SingerId equals sing.SingerId
                         select new ListSong
                         {
                             Id = song.SongId,
                             SongTitle = song.SongTitle,
                             SingerName = sing.SingerName,
                             Views = song.Views,
                             PathMusic = song.PathMusic
                         }).SingleOrDefault(x => x.Id == id).Views;
            
            song1.Views = views + 1;

            ViewBag.SongTitle = db.Songs.SingleOrDefault(x => x.SongId == id).SongTitle;
            ViewBag.PathMusic = db.Songs.SingleOrDefault(x => x.SongId == id).PathMusic;
            ViewBag.SingerName = (from song in db.Songs
                                  join sing in db.Singers on song.SingerId equals sing.SingerId
                                  select new ListSong
                                  {
                                      Id = song.SongId,
                                      SongTitle = song.SongTitle,
                                      SingerName = sing.SingerName,
                                      Views = song.Views,
                                      PathMusic = song.PathMusic
                                  }).SingleOrDefault(x => x.Id == id).SingerName;
            // Cap nhat luot view vao CSDL
            ViewBag.Views = views + 1;

            db.Entry(song1).State = EntityState.Modified;

            db.SaveChanges();


            return View();
        }
    }
}

src/Controllers/HomeController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class HomeController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        public ActionResult Index()
        {
            ViewBag.listSong = (from song in db.Songs
                                join sing in db.Singers on song.SingerId equals sing.SingerId
                                select new ListSong
                                {
                                    Id = song.SongId,
                                    SongTitle = song.SongTitle,
                                    SingerName = sing.SingerName,
                                    Views = song.Views,
                                    PathMusic = song.PathMusic,
                                    SingerId = song.SingerId
                                }).OrderByDescending(x => x.Views).Take(7).ToList();

            ViewBag.listNewSong = (from song in db.Songs
                                   join sing in db.Singers on song.SingerId equals sing.SingerId
                                   select new ListNewSong
                                   {
                                       id = song.SongId,
                                       SongTitle = song.SongTitle,
                                       SingerName = sing.SingerName,
                                       SingerId = sing.SingerId,
                                       DateUpload = song.DateUpload

                                   }).OrderBy(x => x.DateUpload).Take(7).ToList();
            ViewBag.listAblum = db.Albums.ToList();
            ViewBag.listMusician = db.Musicians.ToList();
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(String username, String fullname, String email, String password, String cfpassword)
        {

            if (String.IsNullOrEmpty(username) || String.IsNullOrEmpty(email) || String.IsNullOrEmpty(password) || String.IsNullOrEmpty(cfpassword)||String.IsNullOrEmpty(fullname))
            {
                ViewBag.Error = "Thông tin không được để trống";
                return View();
            }
            if (!password.Equals(password))
            {
                ViewBag.Error = "Mật khẩu phải trùng nhau";
                return View();
            }
            if (password.Length < 6)
            {
                ViewBag.Error = "Mật khẩu có độ dài lớn hơn 6 ký tự";
                return View();
            }
            var nameuser = db.Accounts.Where(x => x.Username == username).ToList();
            if (nameuser.Count>0)
            {
                ViewBag.Error = "Ten da co trong he thong";
                return View();
            }
            Account account = new Account();
            account.Username = username;
            account.Fullname = fullname;
            account.Email = email;
            account.Password = password;
            account.IsAdmin = 0;
            db.Accounts.Add(account);
            db.SaveChanges();
            ViewBag.TB = "Dang ky thanh cong";
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(String username, String password)
        {
            Session["userId"] = null;
            Session["username"] = null;
            Session["fullname"] = null;
            Session["avatar"] = null;
            Session["userId"] = null;

            var user = db.Accounts.SingleOrDefault(x => x.Username == username && x.Password == password && x.IsAdmin == 0);
            if (user != null)
            {
                Session["userId"] = user.UserId;
                Session["username"] = user.Username;
                Session["fullname"] = user.Fullname;
                Session["avatar"] = user.Avatar;
                return RedirectToAction("/");
            }
            ViewBag.Error = "Đăng nhập không thành công";
            return View();
        }
        public ActionResult Forgot()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Forgot(string username, string email)
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session["userId"] = null;
            Session["username"] = null;
            Session["fullname"] = null;
            Session["avatar"] = null;
            return RedirectToAction("/");
        }
        public ActionResult AddFavorite(int id)
        {
            if (Session["userId"] != null)
            {
                int userId = Convert.ToInt32(Session["userId"]);
                var check = db.Favorites.Where(x => x.SongId == id).Where(x => x.UserId == userId).ToList();
                if (check.Count==0)
                {
                    Favorite fav = new Favorite();
                    fav.UserId = userId;
                    fav.SongId = id;
                    db.Favorites.Add(fav);
                    db.SaveChanges();
                }

            }
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

src/Views/Home/Forgot.cshtml
@{
    ViewBag.Title = "Forgot";
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}
<div class="container">
    <form class="form-horizontal" action="Home/Forgot" method="post" style="margin-top: 20px; height: 450px;">
        <div class="form-group">
            <label class="control-label col-md-4">Tên tài khoản</label>
            <div class="col-md-6">
                <input type="text" class="form-control" name="username" placeholder="Nhập tài khoản">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">Email</label>
            <div class="col-md-6">
                <input type="email" class="form-control" name="Email" placeholder="Nhập email">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-md-6">
                <button type="submit" class="btn btn-default">Gửi</button>
            </div>
        </div>
    </form>
</div>

src/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    var stt = 1;
}

<div class="ms-home-top">
    <div class="ms-home-carousel">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="item active">
                    <a href="#"><img src="~/Content/Images/banner.png" style="width:650px; height:280px;"></a>

                </div>
                <div class="item">
                    <a href="#"><img src="~/Content/Images/banner1.jpg" style="width:650px; height:280px;"></a>
                </div>
                <div class="item">
                    <a href="#"><img src="~/Content/Images/banner2.jpg" style="width:650px; height:280px;"></a>
                </div>
                <div class="item">
                    <a href="#"><img src="~/Content/Images/banner3.jpg" style="width:650px; height:280px;"></a>
                </div>
            </div>
            <ul class="subimg">
                <li data-target="#myCarousel" data-slide-to="0" class="active">
                    <a href="#"><img src="~/Content/Images/banner.png" style="width:110px; height:50px;"></a>

                </li>
                <li data-target="#myCarousel" data-slide-to="1">
                    <a href="#"><img src="~/Content/Images/banner1.jpg" style="width:110px; height:50px;"></a>
                </li>
                <li data-target="#myCarousel" data-slide-to="2">
                    <a href="#"><img src="~/Content/Images/banner2.jpg" style="width:110px; height:50px;"></a>
                </li>
                <li data-target="#myCarousel" data-slide-to="3">
                    <a href="#"><img src="~/Content/Images/banner3.jpg" style="width:110px; height:50px;"></a>
                </li>
            </ul>

        </div>
    </div>
    <div class="ms-home-bxh">
        <p>Danh sách bảng xếp hạng</p>
        <ul>
            @foreach (var topmusic in (IEnumerable<MusicViet.Models.ListSong>)ViewBag.listSong)
            {
                <li>
                    <span style="color: blueviolet; font-size: 16px; font-weight: 600;">0@(stt++)</span>
                    @Html.ActionLink(topmusic.SongTitle, "Detail", "DetailSong", new { id = topmusic.Id }, null)

                    <span>Lượt nghe: @topmusic.Views</span>
                </li>
            }

        </ul>
    </div>
</div>
<div class="ms-home-bottom">
    <h3>
        NHẠC MỚI
        <i class="fa fa-angle-right" aria-hidden="true"></i>
    </h3>
    <div class="ms-home-nhacmoi">
        @foreach (var newmusic in ViewBag.listNewSong as List<MusicViet.Models.ListNewSong>)
        {

            <div>
                <img src="~/Content/Images/music.jpg" alt="@newmusic.SongTitle" style="border:1px solid rgba(209, 209, 209, 0.72);">
                @Html.ActionLink(newmusic.SongTitle, "Detail", "DetailSong", new { id = newmusic.id }, new { style = "width:120px;text-align:center; height:40px; display:block;" })
                <div style="text-align:center;">

                    @Html.ActionLink(newmusic.SingerName, "Detail", "DetailArtist", new { id = newmusic.SingerId, artist = "singer" }, new { style = " color: black;" })
                </div>
                
            </div>
        }
    </div>
    <h3>
        NHẠC HOT
        <i class="fa fa-angle-right" aria-hidden="true"></i>
    </h3>
    <div class="ms-home-nhachot">
        @foreach (var hotmusic in ViewBag.listSong as List<MusicViet.Models.ListSong> )
        {
            <div>
                <img src="~/Content/Images/music2.png" alt="@hotmusic.SongTitle" style="border: 1px solid rgba(209, 209, 209, 0.72); width: 120px;height:120px;">
                @Html.ActionLink(hotmusic.SongTitle, "Detail", "DetailSong", new { id = hotmusic.Id }, new { style = "width:120px;text-align:center; height:40px; display:block;" })
                @Html.ActionLink(hotmusic.SingerName, "Detail", "DetailArtist", new { id = hotmusic.SingerId, artist = "singer" }, new { style = " color: black; width:120px;text-align:center; display:block;" })
            </div>
        }
    </div>
    <h3>
        ALBUM MỚI
        <i class="fa fa-angle-right" aria-hidden="true"></i>
    </h3>
    <div class="ms-home-albumnew">
        @foreach (var item in ViewBag.listAblum)
        {
            <div>
                <img src="~/ImageUpload/single.png" alt="" style="border: 1px solid rgba(209, 209, 209, 0.72); width: 120px;height:120px;" />
                <span style="width:120px;text-align:center; padding-top:4px;">@item.AlbumTitle</span>
            </div>
        }

    </div>
    <h3>
        NGHÊ SĨ HOT
        <i class="fa fa-angle-right" aria-hidden="true"></i>
    </h3>
    <div class="ms-home-nghesihot">
        @foreach (var item in ViewBag.listMusician)
        {
            <div>
                <img src="@Url.Content(item.MusicianPic)" alt="" style="border: 1px solid rgba(209, 209, 209, 0.72); width: 120px;height:120px;" />
                <span style="width:120px;text-align:center; padding-top:4px;">@item.MusicianName</span>
            </div>
        }
    </div>
</div>

src/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}
<div class="container" style="margin-top: 20px;height: 450px;">
    @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="control-label col-md-4" for="pwd">Tên tài khoản</label>
            <div class="col-md-6">
                <input type="text" class="form-control" name="username" placeholder="Nhập tài khoản">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-4" for="pwd">Mật khẩu</label>
            <div class="col-md-6">
                <input type="password" class="form-control" name="password" placeholder="Nhập mật khẩu">
            </div>
        </div>
        <div class="form-group">

            <div class="col-sm-offset-4 col-md-6">
                <a href="Register">Tài khoản mới</a>
            </div>
        </div>
        <div class="form-group">

            <div class="col-sm-offset-4 col-md-6">
                <a href="Forgot">Quên mật khẩu</a>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-md-6">
                <button type="submit" class="btn btn-default">Đăng nhập</button>
            </div>
        </div>
    }
    <p style="text-align:center; color: red; margin-top:10px">@ViewBag.Error</p>
</div>

src/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}

<div class="container" style="margin-top: 20px;height: 450px;">
    @using (Html.BeginForm("Register", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="control-label col-md-4"> Nhập họ tên </label>
            <div class="col-md-6">
                <input type="text" class="form-control" name="fullname" placeholder="Nhập họ tên">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">Tên tài khoản</label>
            <div class="col-md-6">
                <input type="text" class="form-control" name="username" placeholder="Nhập tài khoản">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">Email</label>
            <div class="col-md-6">
                <input type="email" class="form-control" name="email" placeholder="Nhập email">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">Mật khẩu</label>
            <div class="col-md-6">
                <input type="password" class="form-control" name="password" placeholder="Nhập mật khẩu">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">Xác nhận mật khẩu</label>
            <div class="col-md-6">
                <input type="password" class="form-control" name="cfpassword" placeholder="Xác nhận lại mật khẩu">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-md-6">
                <button type="submit" class="btn btn-default">Đăng ký</button>
            </div>
        </div>

    }
    <p style="text-align:center; color: red; margin-top:10px">@ViewBag.Error</p>
    <p style="text-align:center; color: blue; margin-top:10px">@ViewBag.TB</p>
</div>